modLoader = "javafml"
loaderVersion = "${loader}"
license = "MIT"
issueTrackerURL = "https://github.com/CoolAid48/NoSignGUI/issues"

[[mods]]
modId = "nosigngui"
version = "${version}"
displayName = "NoSignGUI"
displayURL = "https://coolaid.live/"
logoFile = "assets/nosigngui/icon.png"
authors = "CoolAid48"
displayTest = "IGNORE_ALL_VERSION"
description = '''
Allows you to toggle the sign text interface off and on
'''

[[dependencies.nosigngui]]
modId = "forge"
mandatory = true
versionRange = "${loader}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nosigngui]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
