# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=3.0.0_1.21.4-1.21.8
maven_group=me.coolaid
archives_name=nosigngui
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.8
# Dependencies
fabric_loader_version=0.18.0
fabric_api_version=0.136.1+1.21.8
neoforge_version=21.8.53