modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CoolAid48/NoSignGUI/issues"
license = "MIT"

[[mods]]
modId = "nosigngui"
version = "${version}"
displayName = "NoSignGUI"
authors = "CoolAid48"
description = '''
Allows you to toggle the sign text interface off and on
'''
logoFile = "assets/nosigngui/icon.png"

[[mixins]]
config = "nosigngui.mixins.json"
