modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "nosigngui"
version = "3.0.0"
displayName = "NoSignGUI"
authors = "CoolAid48"
description = '''
Allows you to toggle the sign text interface off and on
'''
logoFile = "assets/nosigngui/icon.png"

[[mixins]]
config = "nosigngui.mixins.json"
